services:
  postgres:
    image: postgres:16-alpine
    container_name: edushare-postgres
    restart: always
    environment:
      POSTGRES_USER: edushare_user
      POSTGRES_PASSWORD: edushare_password
      POSTGRES_DB: edushare_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
